---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-s3
provisioner: ch.ctrox.csi.s3-driver
parameters:
  # specify which mounter to use
  # can be set to rclone, s3fs, goofys or s3backer
  csiProvisionerSecretName: csi-s3-secret
  csiProvisionerSecretNamespace: kube-system
  csiControllerPublishSecretName: csi-s3-secret
  csiControllerPublishSecretNamespace: kube-system
  csiNodeStageSecretName: csi-s3-secret
  csiNodeStageSecretNamespace: kube-system
  csiNodePublishSecretName: csi-s3-secret
  csiNodePublishSecretNamespace: kube-system